AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Vipingo SDA Church Giving Backend

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 256

Parameters:
  MpesaShortCode:
    Type: String
    Description: M-Pesa Short Code
  MpesaConsumerKey:
    Type: String
    Description: M-Pesa Consumer Key
    NoEcho: true
  MpesaConsumerSecret:
    Type: String
    Description: M-Pesa Consumer Secret
    NoEcho: true
  MpesaPasskey:
    Type: String
    Description: M-Pesa Passkey
    NoEcho: true
  TreasurerPhoneNumber:
    Type: String
    Description: Phone number for Treasurer notifications

Resources:
  ### API Gateway
  GivingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'http://localhost:5173'" 
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'POST,GET,OPTIONS,PUT,DELETE'"
        AllowCredentials: "'true'"

  ### Lambda: Giving
  GivingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/giving/
      Handler: giving.handler
      Events:
        GivingPost:
          Type: Api
          Properties:
            Path: /giving
            Method: post
            RestApiId: !Ref GivingApi
      Environment:
        Variables:
          DYNAMO_TABLE: ChurchOfferings
          SNS_TOPIC_ARN: !Ref TreasurerSnsTopic
          MPESA_SHORTCODE: !Ref MpesaShortCode
          MPESA_CONSUMER_KEY: !Ref MpesaConsumerKey
          MPESA_CONSUMER_SECRET: !Ref MpesaConsumerSecret
          MPESA_PASSKEY: !Ref MpesaPasskey
          TreasurerPhoneNumber: !Ref TreasurerPhoneNumber
          MPESA_CALLBACK_URL: https://gttca8x6n1.execute-api.us-east-1.amazonaws.com/prod/mpesa-callback
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ChurchOfferings
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt TreasurerSnsTopic.TopicName

  ### Lambda: M-Pesa Payment
  MpesaPayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/mpesa/
      Handler: mpesa.handler
      Events:
        MpesaPost:
          Type: Api
          Properties:
            Path: /mpesa/
            Method: post
            RestApiId: !Ref GivingApi
      Environment:
        Variables:
          MPESA_SHORTCODE: !Ref MpesaShortCode
          MPESA_CONSUMER_KEY: !Ref MpesaConsumerKey
          MPESA_CONSUMER_SECRET: !Ref MpesaConsumerSecret
          MPESA_PASSKEY: !Ref MpesaPasskey
          MPESA_CALLBACK_URL: https://gttca8x6n1.execute-api.us-east-1.amazonaws.com/prod/mpesa-callback

  ### Lambda: Send SMS
  SendSmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/sms/
      Handler: sms.handler
      Events:
        SmsPost:
          Type: Api
          Properties:
            Path: /sms/
            Method: post
            RestApiId: !Ref GivingApi
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt TreasurerSnsTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref TreasurerSnsTopic

  ### SNS Topic for Treasurer Notifications
  TreasurerSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TreasurerNotifications

  ### Treasurer SMS Subscription
  TreasurerSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref TreasurerSnsTopic
      Protocol: sms
      Endpoint: !Ref TreasurerPhoneNumber

  ## DynamoDB Table
  ChurchOfferingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChurchOfferings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: TransactionID
          AttributeType: S
      KeySchema:
        - AttributeName: TransactionID
          KeyType: HASH